[package]
name = "wasm_component_layer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
fxhash = "0.2.1"
id-arena = "2.2.1"
wasm_runtime_layer = { version = "0.1.1", features = [ "backend_wasmi" ] }
wasmtime-environ = { git = "https://github.com/bytecodealliance/wasmtime", branch = "release-12.0.0", features = [ "component-model" ] }
wit-component = { version = "0.13.1" }
wit-parser = "0.9.2"

[dev-dependencies]
wasmi = "0.31.0"